auth:
  storage_path: ${AUTH_STORAGE_PATH}
  email: ${EMAIL}
  password: ${PASSWORD}

qna:
  storage_path: ${QNA_STORE_PATH:-./qna.json}   # fallback default

search:
  time_range: past24h
  job_limit: 3
  position: Backend developer
  location: Indonesia
  company_blacklist:
    - Diksha
    - Super indo
